apiVersion: apps/v1
kind: Deployment
metadata: {name: be-service}
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app
        env:
        - {name: APP_ENV, value: staging}
        - {name: DEMO_MODE, value: "false"}
        - {name: DEMO_FAULT, value: "false"}
