---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: be-service-secret
  namespace: staging
spec:
  encryptedData:
    DB_PASSWORD: AgAuhX4W1tX3AKlLtipapRGQjk9CbQAwB4/6baCSPT8UzsEf2e/naWK1vE74VtKIWRhBxOPNjHnk70e1yejveLZsCG3tOOn/OV1Eun7+p0M19Cc9/iYkd+Psd1TgqCUldOC61n/D4psxhGH58uwkFr05xkPvCnuZHSEWA/CpxjpyKZ8awfIdD7Ax37emis/LFbiTKzSSEKjo246qIuhxAetk5BiLBSWYLTLP6AwFLbVQVn7X0m/OithnE+ZyVwBnb/fCe3gCJhL5S0BTOsyQmjLAe0wnTRn1qVS3jMng4COVSRC0snQTTJ7dtLZkI0fCGEDTr0fQ+qLthTBSRqy8aZNB7xjG+mOetp3OojNt3yzYDm9Q6KhTj3AoUNCATdyOVNA7t3QdYbpXGwFxVKFQMn2ASntLItPYTwuzpIo02IzZSVmow0H+okGVtq4JozJkdDeakIBxu3OosCBYWvcaV/UZtCZwBY1k2PZSqCZINZu1nOPyS7US7IA74er1G7sYRBOnCZQm1TvpbeiWw7xLzzO+zFVuaKpCPvA3aM3tRm6qui4yudIl+cML9K34Z1UVIH8UT6klZNrcEi44/TB/AVDCNWWc/585PJW1bXSxwqjMuUchOmTAhUBYN0qTUQYMLhVWlzPJnjv7/MpYhozv5D3laC7UM754mjJsyrL4PO0250iJIwmUE9dlODXEmCqSQf9JiW+EBW79kJ+B4yEacYl6Zul4HyvisAGwZfU39XVNk+RyvN391v7Tk+13LKFGXhg=
  template:
    metadata:
      name: be-service-secret
      namespace: staging
    type: Opaque
