apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.127.0.0.1.nip.io
    target:
      kind: Ingress
      name: be-service
  - path: deployment-env-patch.yaml
resources:
  - ../../base
  - sealed-secret.yaml
