---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: be-service-secret
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgCuDXuEa/HBln0P7GvjgHXXYvzxGhoU9M1G1BOt5267SdTlZBZ5Pc+5nfGpZnI9178LV4RXN27Hn6fGTJg1CsXG83EXqTDroHUiL1GObq5Qz/h1LU8j+ujz3fiY5nsMLcd7lk07x5k3ng+sswV9XlrFyYltOdlKJSXHi/oDePySUyPt0BED5fBhtxQvVZXR4ur5om9k3gfD/PWSkTsVyvm5/71cMocu8k2MZXmf9ZCnuwVzQjCCMbAAypo4TSPeB59U+a6MvPDyeHAwWRcfy7TxSzo/uC8wPVvFjZfAVRNWSXutcb7Xr6056NYT9m9ZeiNSvQzTdZasLmNTfseDol8T5B70Hx/euJqAiVAdIcyocFvRCetzM5zAQG3/WZEjL37wUrp1be3oQsyOIpuS/JYBUT9+APdeza3xOYV03KJjY4CBhPwPUZkaSJ3VqSC9pUYnXbSmQQyXzw45ST+iDzEMpXFluYjMU5RhamKKTaRcZANuQWy2KYpDKjGwXKHz9t+OsdZlZViwfXiRFMflQ2fRyyVOP+z5oAbu8BJzinELeXGS3kTBAsHRFqHTVae+SkXH4uC1bG/ThtLRiVuhpUS1SQBy0wVmrzyJWy88lVNjy/z5K7QfNjzSKJwzU075ZBD4yEuZBkD+7oXitGHW04PKLKk10wRDOSxa8t3uAnF/fEXh8M+CwJ1IvajhpJl8EsgMg1qaC7fwjyECAZn40a5cFMZbKEB8GtcE46r4JbZb+ZA1WY7CgkOaUkmbEBtMGXo=
  template:
    metadata:
      name: be-service-secret
      namespace: dev
    type: Opaque
