apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: be-service-ENVIRONMENT
  namespace: argocd
spec:
  project: default
  source:
    repoURL: CONFIG_REPO_URL
    targetRevision: dev
    path: apps/be-service/envs/ENVIRONMENT
  destination:
    server: https://kubernetes.default.svc
    namespace: ENVIRONMENT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
