apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: be-service
    app.kubernetes.io/part-of: gitops-demo

images:
- digest: sha256:aca7a65ed156f8361a53cca1716483ddac1e345bd414501c6d89faac71a8ff3b
  name: ghcr.io/example/be-service
  newName: ghcr.io/namnd74/be-service
