apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: be-service
    app.kubernetes.io/part-of: gitops-demo

images:
- digest: sha256:717d68ed51cbb13ef9a520521adf62322dad6d96d112fb3a3645a789c5bd9519
  name: ghcr.io/example/be-service
  newName: ghcr.io/namnd74/be-service
