apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: be-service-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/namnd74/gitops-manifests.git
    targetRevision: staging
    path: apps/be-service/envs/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
