apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: be-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git://gitops-source.gitops-system.svc.cluster.local/config.git
    targetRevision: main
    path: apps/be-service/envs/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
