apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: be-service-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/namnd74/gitops-manifests.git
    targetRevision: prod
    path: apps/be-service/envs/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
