apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: be-service-secret
  namespace: prod
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    DB_PASSWORD: AgB8w...mock_encrypted_prod_secret_data_generated_by_kubeseal...==
  template:
    metadata:
      name: be-service-secret
      namespace: prod
    type: Opaque
    data: null
