---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: be-service-secret
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCIyTSdLWio2A74gYD/UUSHE/JAWu2AEYmmAaA2EY5rEZc5kNp+4go4NrccX9sV8BrBlS88vNKwpwnQSywz/Xy+7GAo8s/hOocqUi8UWOCmeKAICVhE1wr2CIRdLUNx4rzxsrdhvrRvP9FjgWb1IrUP5MyCzlmy2xcadoRt8Vg6d9nFp/UQWmBzCEZ/klAEcyuD6Zp67ysga2D/WXI7XHpgj1eQ1VUM94EeGzbRLjYEhKt6H46pesMx7j4npGb8A50hwizdZIiT8fQQrkTkFtobMQGX65cSYgfAovcMMFakxBG1rE7zyj2MeeG7/eze3hg+3tuqadj7qqVoNhWH7tlTazO5ZLYdviKz/r6BiOUOR2Z66gnMCI4e8imYk1OsadPK+9j5+LZYvGONBLGVtv1E0xS6jfqlO8kD/Gvs7tE7tHwqPYi77wpNlpROiONX/KkZ/gZ+4ZZPkIFFp8tSATUcoV2V0aSlsmfRFP8vIyth9hotUyCAXi7fvQGhu5x60mv2l9zkyqtxB4ADog4WAoEXSeTlWsrWzwWokKTEL1baKpaCpVmjxCa0JLPwOicFbNoI7VvdfqzSYtW8NSAgCMtDAquAX2D0yt5qQhU6gBFunjHRzV6ScmqTj/30OB0suGRQSxORC7a7/gz00jbSBuUqCofjKE+glYTkIIMkn3h4hPqXsR5+eYhFo5+vBhDjmv92/4SMIqWKIVVlkaKQi0gaJPZ13T0OyK4EYubuBv57L2mzrvsm5zNCrFMlvRLxu84=
  template:
    metadata:
      name: be-service-secret
      namespace: prod
    type: Opaque
